
friends = ["Captain America", "Iron Man", "Thor", "The Incredible Hulk", "Black Widow", "Star Lord", "Rocket Raccoon"]
print(friends)
print(friends[2])
print(friends[2:5])
friends.insert(2, "Nova")
print(friends)
# print(friends[0] + " is a principled character. " + friends[7] ", however, is not principled")
friends.remove("Star Lord")
print(friends)
print(friends.index("Thor"))
print(friends.insert(3, "Star Lord"))
print(friends)
print(friends.index("Rocket Raccoon"))
friends.pop()
print(friends)
friends.insert(7, "Rocket Raccoon")
print(friends)
friends.sort()
print(friends)
friends.reverse()
print(friends)
